# Generated by Django 2.2.1 on 2019-06-07 14:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_field_values_summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A summary of all unique differences between the alias instances and the primary instance', null=True)),
                ('alias_field_values', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='A list of dicts, each containing the differences between the primary instance and an alias instance', null=True)),
                ('num_instances_merged', models.PositiveIntegerField(help_text='The number of model instances that were merged together (including the primary)')),
            ],
        ),
    ]
